server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800

spring:
  profiles:
    active: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  jpa:
    properties:
      hibernate.format_sql: true
logging:
  level:
    org.hibernate.type: TRACE
    org.hibernate.SQL: DEBUG


my.name: ApplicationProperties
contextPath: /app
port: 9090

