server:
  port: 9090
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800
    context-path: /app

spring:
  profiles:
    active: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    properties:
      hibernate.format_sql: true
logging:
  level:
    org.hibernate.type: TRACE
    org.hibernate.SQL: DEBUG